swagger: '2.0'
info:
  version: '1.0.0'
  title: Soup Snakes - Users
  description: An API to keep track of Soup Snakes users
  contact:
    name: Jake Krammer
    email: jake.krammer1@gmail.com
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      description: Returns all Soup Snake users
      operationId: findUsers
      produces:
        - application/json
      responses:
        '200':
          description: user response
          schema:
            type: array
            items:
              $ref: '#/definitions/user'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    post:
      description: Creates a new user. 
      operationId: addUser
      produces:
        - application/json
      parameters:
        - name: user
          in: body
          description: User to add
          required: true
          schema:
            $ref: '#/definitions/newUser'
      responses:
        '200':
          description: user response
          schema:
            $ref: '#/definitions/user'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /users/{id}:
    get:
      description: Returns a user by id
      operationId: findUserById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of user to fetch
          required: true
          type: string
      responses:
        '200':
          description: user response
          schema:
            $ref: '#/definitions/user'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    delete:
      description: deletes a single user based on the ID supplied
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          description: ID of user to delete
          required: true
          type: string
      responses:
        '204':
          description: user deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  user:
    type: object
    required:
      - id
      - name
      - partnerId
    properties:
      id:
        type: string
      name:
        type: string
      partnerId:
        type: string
  newUser:
    type: object
    required:
      - name
    properties:
      id:
        type: string
      name:
        type: string
      partnerId:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
